name: Preorder Release Cleanup

permissions:
  contents: write
  issues: write

on:
  schedule:
    - cron: '0 4 * * 2'  # Run at 12:00 AM Eastern Time (4:00 AM ET is UTC +4)
  workflow_dispatch:

jobs:
  preorder-release-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create environment file
        run: |
          echo "SHOP_URL=${{ secrets.SHOP_URL }}" > .env.production
          echo "SHOPIFY_ACCESS_TOKEN=${{ secrets.SHOPIFY_ACCESS_TOKEN }}" >> .env.production
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env.production
          echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> .env.production
          echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> .env.production
          echo "USE_TEST_DATA=false" >> .env.production
          echo "🚀 Running in PRODUCTION mode"

      - name: Run preorder manager
        run: |
          python -u preorderManager.py