name: Preorder Approval Workflow

on:
  # Run weekly on Friday to prepare for the Monday report
  schedule:
    - cron: '0 0 * * 5'  # Midnight on Friday
  
  # Allow manual trigger
  workflow_dispatch:
    inputs:
      run_mode:
        description: 'Run mode (test or production)'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - production

jobs:
  audit-and-approval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create environment file
        run: |
          echo "SHOP_URL=${{ secrets.SHOP_URL }}" > .env.production
          echo "SHOPIFY_ACCESS_TOKEN=${{ secrets.SHOPIFY_ACCESS_TOKEN }}" >> .env.production
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" >> .env.production
          echo "EMAIL_SENDER=${{ secrets.EMAIL_SENDER }}" >> .env.production
          echo "EMAIL_RECIPIENTS=${{ secrets.EMAIL_RECIPIENTS }}" >> .env.production
          
          # Set test mode based on input parameter
          if [ "${{ github.event.inputs.run_mode }}" = "test" ]; then
            echo "USE_TEST_DATA=true" >> .env.production
            echo "🧪 Running in TEST mode"
          else
            echo "USE_TEST_DATA=false" >> .env.production
            echo "🚀 Running in PRODUCTION mode"
          fi
      
      - name: Run publication date audit
        id: run-audit
        run: |
          mkdir -p output audit overrides
          TIMESTAMP=$(date +'%Y-%m-%d')
          RELEASES_FILE="./output/pending_releases_${TIMESTAMP}.json"
          
          # Run the audit and save all output for examination
          python audit_publication_dates.py --output-releases "$RELEASES_FILE" --test-mode > audit_output.log 2>&1
          
          # Show the log
          echo "==== AUDIT LOG START ===="
          cat audit_output.log
          echo "==== AUDIT LOG END ===="
          
          echo "releases_file=$RELEASES_FILE" >> $GITHUB_OUTPUT
          
          # See if the file exists
          if [ -f "$RELEASES_FILE" ]; then
            echo "File exists: $RELEASES_FILE"
          else
            echo "File does not exist: $RELEASES_FILE"
            echo "Trying to find any pending_releases files:"
            find / -name "pending_releases*" 2>/dev/null || echo "No files found"
          fi
      
      - name: Check for pending releases
        id: check-releases
        run: |
          RELEASES_FILE="${{ steps.run-audit.outputs.releases_file }}"
          if [ ! -f "$RELEASES_FILE" ] && [ -n "${{ steps.create-manual-file.outputs.manual_file }}" ]; then
            RELEASES_FILE="${{ steps.create-manual-file.outputs.manual_file }}"
            echo "Using manual test file instead: $RELEASES_FILE"
          fi
          
          if [ -f "$RELEASES_FILE" ]; then
            cat "$RELEASES_FILE"  # Show file contents
            PENDING_COUNT=$(python -c "import json; f=open('$RELEASES_FILE'); data=json.load(f); print(data.get('total_pending_books', 0))")
            echo "Found $PENDING_COUNT pending book releases"
            echo "pending_count=$PENDING_COUNT" >> $GITHUB_OUTPUT
            echo "releases_file=$RELEASES_FILE" >> $GITHUB_OUTPUT
          else
            echo "No pending releases file found"
            echo "pending_count=0" >> $GITHUB_OUTPUT
          fi
      
      - name: Create approval issue
        if: steps.check-releases.outputs.pending_count > '0'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const releasesFile = '${{ steps.check-releases.outputs.releases_file }}';
            console.log(`Reading releases from: ${releasesFile}`);
            
            // Check if file exists and list directory contents
            try {
              fs.accessSync(releasesFile, fs.constants.F_OK);
              console.log(`File exists: ${releasesFile}`);
              
              const fileStats = fs.statSync(releasesFile);
              console.log(`File size: ${fileStats.size} bytes`);
              
              const dirName = require('path').dirname(releasesFile);
              const dirContents = fs.readdirSync(dirName);
              console.log(`Directory contents of ${dirName}:`, dirContents);
              
              const pendingData = JSON.parse(fs.readFileSync(releasesFile, 'utf8'));
              const timestamp = new Date().toISOString().split('T')[0];
          
            // Format books as a markdown table
            let booksTable = '| Approve | ISBN | Title | Quantity | Pub Date | Publisher |\n|---------|------|-------|----------|----------|----------|\n';
            
            pendingData.pending_releases.forEach(book => {
              booksTable += `| [ ] | ${book.isbn} | ${book.title} | ${book.quantity} | ${book.pub_date || 'Unknown'} | ${book.vendor || 'Unknown'} |\n`;
            });
            
            // Create issue with approval checkboxes
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `📚 Preorder Approval: ${pendingData.total_pending_books} Books Ready for Release (${timestamp})`,
              body: `## Preorder Books Ready for Release Approval

            **Important: Please review these preorder books before they are included in the weekly sales report.**

            Check the boxes for books that should be included in this week's report. Books with unchecked boxes will remain in preorder status.

            ### Instructions
            1. Review each book's details
            2. Check the box in the "Approve" column for books that should be included
            3. Add the label \`approved\` to this issue when you've finished reviewing
            4. Only checked books will have their sales included in the next report

            ### Books Pending Approval

            ${booksTable}

            ### Notes
            - This approval is required by: Monday at 8:00 AM
            - Books not approved will remain in preorder status
            - Data file: \`${releasesFile}\``,
                  labels: ['pending-approval', 'preorders']
                });
                
                console.log(`Created approval issue #${issue.data.number}`);
      
      - name: Upload pending releases file
        if: steps.check-releases.outputs.pending_count > '0'
        uses: actions/upload-artifact@v4
        with:
          name: pending-releases
          path: ${{ steps.run-audit.outputs.releases_file }}

      - name: Create manual test file if needed
        run: |
          RELEASES_FILE="${{ steps.run-audit.outputs.releases_file }}"
          if [ ! -f "$RELEASES_FILE" ]; then
            echo "Creating manual test file because audit didn't create one"
            MANUAL_FILE="./output/pending_releases_manual.json"
            cat > $MANUAL_FILE << 'EOF'
            {
              "pending_releases": [
                {
                  "isbn": "9780262551311",
                  "title": "Modern Chinese Foodways",
                  "quantity": 2,
                  "pub_date": "2025-03-01"
                },
                {
                  "isbn": "9784756256522",
                  "title": "Fishes of Edo: A Guide to Classical Japanese Fishes",
                  "quantity": 10,
                  "pub_date": "2025-03-01" 
                }
              ],
              "error_cases": [],
              "total_quantity": 12,
              "run_date": "2025-03-11",
              "total_pending_books": 2
            }
            EOF
            
            echo "manual_file=$MANUAL_FILE" >> $GITHUB_OUTPUT
            echo "Created manual test file: $MANUAL_FILE"
            cat $MANUAL_FILE
          else
            echo "Audit file exists, no need to create manual file"
          fi