name: Refresh Preorder Product IDs

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day at 6:00 AM UTC (2:00 AM US Eastern Time)
  workflow_dispatch: # Allow manual trigger from GitHub if needed

jobs:
  refresh-preorder-ids:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Debug print environment variables
        run: |
          echo "SHOP_URL starts with: ${SHOP_URL:0:8}"
          echo "STOREFRONT_ACCESS_TOKEN length: ${#STOREFRONT_ACCESS_TOKEN}"
        env:
          SHOP_URL: ${{ secrets.SHOP_URL }}
          STOREFRONT_ACCESS_TOKEN: ${{ secrets.STOREFRONT_ACCESS_TOKEN }}

      - name: Run refreshPreorderProductIDs.py
        env:
          SHOP_URL: ${{ secrets.SHOP_URL }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        run: |
          python refreshPreorderProductIDs.py
