name: Tag Preorder Orders

on:
  schedule:
    - cron: "0 * * * *" # Runs at the start of every hour
  workflow_dispatch: # Allow manual trigger from GitHub if needed

jobs:
  tag-preorder-orders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system CA certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Install dependencies and certificates
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv requests certifi

      - name: Set SSL_CERT_FILE environment variable
        run: echo "SSL_CERT_FILE=$(python -m certifi)" >> $GITHUB_ENV

      - name: Run preorderOrderTagger.py
        env:
          SHOP_URL: ${{ secrets.SHOP_URL }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
        run: |
          python preorderOrderTagger.py
