def load_environment(env):
    """
    Loads environment variables from the specified .env file based on the environment.
    """
    if os.getenv("SHOP_URL") and os.getenv("SHOPIFY_ACCESS_TOKEN"):
        print("Environment variables detected. Skipping .env file loading.")
        return

    env_files = {
        'production': '.env.production',
        'test': '.env.test'
    }

    if env not in env_files:
        print(f"Error: Unknown environment '{env}'. Choose from 'production' or 'test'.")
        sys.exit(1)

    env_file = env_files[env]

    if not os.path.exists(env_file):
        print(f"Error: Environment file '{env_file}' does not exist.")
        sys.exit(1)

    load_dotenv(dotenv_path=env_file)
    print(f"Loaded environment variables from '{env_file}'.")
