name: Generate Weekly Report

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 1"  # 10am ET Monday during DST (EDT)

permissions:
  contents: write

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Match your test version
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4  # Match your test version
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Generate and send report
        env:
          SHOP_URL: ${{ secrets.SHOP_URL }}
          SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECIPIENTS: ${{ secrets.EMAIL_RECIPIENTS }}
        run: python3 weekly_sales_report.py
        
      - name: Commit and push updated tracking file
        if: success()
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add preorders/NYT_preorder_tracking.csv
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update preorder tracking data [skip ci]" && git push)
      
      - name: Upload report artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sales-reports
          path: output/
